RestaurantMVC.UI/Areas/Admin/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace RestaurantMVC.UI.Areas.Admin.Controllers
{
    public class LayoutController : Controller
    {
        public PartialViewResult HeadPartial()
        {
            return PartialView();
        }

        public PartialViewResult SideHeaderPartial()
        {
            return PartialView();
        }

        public PartialViewResult SideMenuPartial()
        {
            return PartialView();
        }

        public PartialViewResult HeaderPartial()
        {
            return PartialView();
        }

        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }

        public PartialViewResult ScriptsPartial()
        {
            return PartialView();
        }
    }
}

RestaurantMVC.UI/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Core.Services;
using RestaurantMVC.UI.Areas.Admin.ViewModels;

namespace RestaurantMVC.UI.Controllers
{
    public class AboutController : Controller
    {
        private readonly IAboutService _aboutService;

        public AboutController(IAboutService aboutService)
        {
            _aboutService = aboutService;
        }

        public IActionResult Index()
        {
            var about = _aboutService.GetAllAsync().Result.OrderByDescending(x => x.CreatedDate).Take(1).ToList();
            var aboutViewModel = about.Select(x => new AboutViewModel
            {
                Title = x.Title,
                Description = x.Description,
            });

            return View(aboutViewModel);
        }
    }
}

RestaurantMVC.UI/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Core.Helpers;
using RestaurantMVC.Core.Services;
using RestaurantMVC.UI.Areas.Admin.ViewModels;

namespace RestaurantMVC.UI.Controllers
{
    public class LayoutController : Controller
    {
        private readonly ISliderService _sliderService;

        public LayoutController(ISliderService sliderService)
        {
            _sliderService = sliderService;
        }

        public PartialViewResult HeadPartial()
        {
            return PartialView();
        }

        public PartialViewResult SpinnerPartial()
        {
            return PartialView();
        }

        public PartialViewResult NavbarPartial()
        {
            return PartialView();
        }

        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }

        public PartialViewResult ScriptsPartial()
        {
            return PartialView();
        }
    }
}

RestaurantMVC.UI/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Core.Helpers;
using RestaurantMVC.Core.Services;
using RestaurantMVC.UI.Areas.Admin.ViewModels;
using X.PagedList;

namespace RestaurantMVC.UI.Controllers
{
    public class MenuController : Controller
    {
        private readonly IProductService _productService;

        public MenuController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int page = 1, int pageSize = 5)
        {
            var products = await _productService.GetProductsWithCategory();
            var productViewModel = products.Select(x => new ProductViewModel
            {
                Name = x.Name,
                Description = HtmlHelper.StripHtml(x.Description),
                Price = x.Price,
                ImageURL = x.ImageURL,
                CategoryId = x.CategoryId,
            }).ToPagedList(page, pageSize);

            return View(productViewModel);
        }

    }
}

RestaurantMVC.UI/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Core.Services;
using RestaurantMVC.UI.Areas.Admin.ViewModels;

namespace RestaurantMVC.UI.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IServicesService _servicesService;

        public ServiceController(IServicesService servicesService)
        {
            _servicesService = servicesService;
        }

        public async Task<IActionResult> Index()
        {
            var services = await _servicesService.GetAllAsync();
            var servicesViewModel = services.Select(x => new ServiceViewModel
            {
                Title = x.Title,
                Description = x.Description,
                Logo = x.Logo
            }).ToList();

            return View(servicesViewModel);
        }
    }
}

RestaurantMVC.UI/Controllers/StaffController.cs
using Microsoft.AspNetCore.Mvc;
using RestaurantMVC.Core.Services;
using RestaurantMVC.UI.Areas.Admin.ViewModels;

namespace RestaurantMVC.UI.Controllers
{
    public class StaffController : Controller
    {
        private readonly IStaffService _staffService;

        public StaffController(IStaffService staffService)
        {
            _staffService = staffService;
        }

        public async Task<IActionResult> Index()
        {
            var staff = await _staffService.GetAllAsync();
            var staffViewModel = staff.Select(x => new StaffViewModel
            {
                FirstName = x.FirstName,
                LastName = x.LastName,
                Title = x.Title,
                ImageURL = x.ImageURL,
                SocialMedia1 = x.SocialMedia1,
                SocialMedia2 = x.SocialMedia2,
                SocialMedia3 = x.SocialMedia3,
            }).ToList();

            return View(staffViewModel);
        }
    }
}

RestaurantMVC.UI/Views/Layout/FooterPartial.cshtml
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                <a class="btn btn-link" asp-area="" asp-controller="About" asp-action="Index">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Reservation</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@restaurantmvc.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                <h5 class="text-light fw-normal">Monday - Saturday</h5>
                <p>09AM - 09PM</p>
                <h5 class="text-light fw-normal">Sunday</h5>
                <p>10AM - 08PM</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                    Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

RestaurantMVC.UI/Views/Layout/HeadPartial.cshtml
<head>
    <meta charset="utf-8">
    <title>Restaurant MVC</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/assets-frontend/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/assets-frontend/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/assets-frontend/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets-frontend/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets-frontend/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/assets-frontend/css/style.css" rel="stylesheet">
</head>

RestaurantMVC.UI/Views/Layout/NavbarPartial.cshtml
@{
    string controllerName = ViewContext.RouteData.Values["Controller"].ToString();
    string actionName = ViewContext.RouteData.Values["Action"].ToString();
}
@{
    if (ViewContext.RouteData.Values["Controller"].ToString() == "Home" && ViewContext.RouteData.Values["Action"].ToString() == "Index")
    {
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Restoran</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Home" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Home</a>
                        <a asp-area="" asp-controller="About" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "About" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">About</a>
                        <a asp-area="" asp-controller="Service" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Service" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Service</a>
                        <a asp-area="" asp-controller="Menu" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Menu" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Menu</a>
                        <a asp-area="" asp-controller="Staff" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Staff" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Staff</a>
                    </div>
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="btn btn-primary py-2 px-4">Admin Panel</a>
                </div>
            </nav>

            @await Component.InvokeAsync("Slider")
        </div>
    }
    else
    {
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Restoran</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Home" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Home</a>
                        <a asp-area="" asp-controller="About" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "About" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">About</a>
                        <a asp-area="" asp-controller="Service" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Service" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Service</a>
                        <a asp-area="" asp-controller="Menu" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Menu" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Menu</a>
                        <a asp-area="" asp-controller="Staff" asp-action="Index" class="nav-item nav-link @(ViewContext.RouteData.Values["Controller"]!.ToString() == "Staff" && ViewContext.RouteData.Values["Action"]!.ToString() == "Index" ? "active" : "")">Staff</a>
                    </div>

                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="btn btn-primary py-2 px-4">Admin Panel</a>
                </div>
            </nav>

            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container text-center my-5 pt-5 pb-4">
                    @if (controllerName == "About")
                    {
                        <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
                    }
                    else if (controllerName == "Service")
                    {
                        <h1 class="display-3 text-white mb-3 animated slideInDown">Service</h1>
                    }
                    else if (controllerName == "Menu")
                    {
                        <h1 class="display-3 text-white mb-3 animated slideInDown">Menu</h1>
                    }
                    else if (controllerName == "Staff")
                    {
                        <h1 class="display-3 text-white mb-3 animated slideInDown">Staff</h1>
                    }
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">@controllerName</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    }
}

RestaurantMVC.UI/Views/Layout/ScriptsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/assets-frontend/lib/wow/wow.min.js"></script>
<script src="~/assets-frontend/lib/easing/easing.min.js"></script>
<script src="~/assets-frontend/lib/waypoints/waypoints.min.js"></script>
<script src="~/assets-frontend/lib/counterup/counterup.min.js"></script>
<script src="~/assets-frontend/lib/owlcarousel/owl.carousel.min.js"></script>
<script src="~/assets-frontend/lib/tempusdominus/js/moment.min.js"></script>
<script src="~/assets-frontend/lib/tempusdominus/js/moment-timezone.min.js"></script>
<script src="~/assets-frontend/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>
<script src="~/assets-frontend/js/main.js"></script>

RestaurantMVC.UI/Views/Layout/SpinnerPartial.cshtml
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>